employee/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
# for Image 
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
     url(r'^home/$', views.employee_home,
        name="employee_home"),

    url(r'^signup/$', views.employee_register,
        name="employee_register"),


    url(r'^profile/(?P<pk>\d+)$', views.employee_display,
        name="employee_display"),

    url(r'^employee/$', views.employee_list,
        name="employee_list"),                                   

    url(r'^employee/add$', views.employee_create,
        name="employee_create"),                                   

    url(r'^employee/(?P<pk>\d+)/update/$',
        views.employee_update, name="employee_update"),            
        
        

 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payroll/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import employee
from employee import views
import company
from company import views
# from rest_framework import routers, serilizers, viewsets     #This import is for Rest Framework


# class UserSerializer(serializers.HyprlinkdModelSerializer):
#     class Meat:
#         model = employee
#         fields = ('url', 'first_name', 'email', 'last_name')


# class UserViewSet(viewsets.ModelViewSet):
#     queryset = employee.objects.all()
#     serializer_class = UserSerializer


# router = routers.DefaultRouter()
#router.Register(r'employee', UserViewSet)
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("account.urls")),
    url(r'', include("employee.urls")),
    url(r'', include("company.urls")),
    url(r'', include("attendance.urls")),
    url(r'', include("salary.urls")),
    #url(r'^api-auth/', include('rest_framework.urls')),

]

salary/urls.py
from django.conf.urls import url

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


from . import views


urlpatterns = [
    url(r'^salary/select/$', views.salary, name='select_salary'),

    url(r'^salary/add/$', views.salary_add, name='add_salary'),

    url(r'^salary/history/$', views.salary_history, name='salary_history'),

    url(r'^appraisal/history/$', views.appraisal_history, name='appraisal_history'),

    url(r'^salary/(?P<pk>\d+)/(?P<month>\d+)/(?P<year>\d+)/calculate/$',
        views.employee_salary, name='salary'),

    url(r'^salary/(?P<pk>\d+)/slip/$', views.export, name='salary_slip'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

attendance/models.py
from django.db import models
from django.utils import timezone
import employee
from employee.models import Employee
from company.models import Company
from datetime import date
from django.utils.timezone import now


class Attendance(models.Model):

    MARK_FOR_ATTENDANCE = (
        (1, 'PRESENT'),
        (0, 'ABSENT'),
        (0.5, 'HALF DAY'),
    )

    LEAVE_TYPE = (
        ('C', 'CASUAL LEAVE'),
        ('P', 'PRIVILEGE LEAVE'),
        ('S', 'SEEK LEAVE'),
    )
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    date = models.DateField(
        auto_now=False, auto_now_add=False, default=timezone.now)
    mark = models.FloatField(
        blank=False, null=False, default=1, choices=MARK_FOR_ATTENDANCE)
    leave_type = models.CharField(
        max_length=16, blank=True, null=True, choices=LEAVE_TYPE)
    rem_privilege_leave = models.IntegerField(blank=True, null=True)
    rem_casual_leave = models.IntegerField(blank=True, null=True)
    loss_of_pay = models.IntegerField(default=0)

    def __str__(self):
        return '{}'.format(self.employee.user.first_name)


class LeaveApplication(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    leave_from = models.DateField()
    leave_to = models.DateField()
    leave_type = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return '{},{},'.format(self.employee.first_name, self.leave_type)

employee/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.timezone import now

from decimal import Decimal
import company
import attendance
from company.models import JobType, Designation, Department, Company
from django.contrib.auth.models import User


class Employee(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    middle_name = models.CharField(max_length=12, null=True)
    contact = models.CharField(
        max_length=12, blank=False, null=False, default='0')
    birth_date = models.DateField()
    address = models.TextField(max_length=200)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    profile_photo = models.ImageField(
        upload_to='payroll', height_field=None, width_field=None, max_length=100, null=True)

    def __str__(self):

        return '{} {}'.format(self.user.first_name, self.user.last_name)
    
class EmployeeSalary(models.Model):
    employee = models.ForeignKey(Employee)
    salary = models.DecimalField(decimal_places=2,
                                 max_digits=10,
                                 default=Decimal('0.0000000000')
                                 )
    updation_date = models.DateField(default=timezone.now)
    effective_from = models.DateField()

    def __str__(self):
        return self.employee.user.first_name + str(self.updation_date) + str(self.effective_from)


class DesignationHistory(models.Model):

    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    designation = models.ForeignKey(Designation, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}{}{}'.format(self.employee, self.date, self.designation)

    def add_history(self):
        self.date = timezone.now()
        self.save()


class DepartmentHistory(models.Model):

    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    date = models.DateField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return '{}{}{}'.format(self.employee, self.date, self.department)


class JobTypeHistory(models.Model):

    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    jobtype = models.ForeignKey(JobType, on_delete=models.CASCADE)
    date = models.DateField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return '{}{}{}'.format(self.employee, self.jobtype, self.date)


class LeaveHistory(models.Model):

    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    attendance = models.ForeignKey('self', on_delete=models.CASCADE)
    date = models.DateField(auto_now=True, auto_now_add=False)
    peivilege_leave = models.CharField(max_length=50, blank=True, null=False)
    casual_leave = models.CharField(max_length=50, blank=True, null=False)

    def __str__(self):

        return '{}{}{}'.format(self.employee, self.attendence, self.date)

employee/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.shortcuts import redirect
# Create your views here.
from .models import Employee, DesignationHistory
from django.views.generic import ListView
from .forms import AddEmployeeForm, UserForm, LoginForm, DesignationHistoryForm, JobTypeHistoryForm, DepartmentHistoryForm
from company.models import Designation, WorkType, Department, JobType

# Import For Employee Registration
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm
from django.contrib import messages
# Company Add
import company
from company.models import Company
from company.forms import CompanyForm


# For Employee Profile
from django.utils import timezone
import datetime
from django.contrib.auth.models import User
from salary.models import Salary

# For Company Add

from .models import Company, DepartmentHistory

# import for Email
from django.conf import settings
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from django.template import loader
from django.template.loader import render_to_string
from django.utils.html import strip_tags

# import for chart
from django.db.models import Count, Q

from django.contrib.auth.decorators import login_required


def employee_register(request):

    print("sjhjdsh", request.user)
    if request.method == 'POST':
        print(request.POST)
        form = UserForm(request.POST or None)
        company_add = CompanyForm(request.POST or None)
        employee_form = AddEmployeeForm(request.POST or None, request.FILES)

        if company_add.is_valid() and form.is_valid() and employee_form.is_valid():

            try:
                

                company = company_add.save()
                user = form.save()
                employee = employee_form.save(commit=False)
                employee.company = company
                employee.user = user
                employee = employee_form.save()
                messages.success(request, 'Registration successfull')
                return render(request, 'signup_complete.html', {})
            except:
                print('Exception occures..! ')
        else:
            messages.error(request, 'Form is Not Valid')
            form = UserForm()
            company_add = CompanyForm()
            employee_form = AddEmployeeForm()
            context = {
                'company_add': company_add,
                'form': form,
                'employee_form': employee_form,
            }
            return render(request, 'Signup.html', context)

    else:
       
        form = UserForm()
        company_add = CompanyForm()
        employee_form = AddEmployeeForm()
    context = {
        'company_add': company_add,
        'form': form,
        'employee_form': employee_form,
    }
    return render(request, 'Signup.html', context)


def employee_list(request):
    print(request.user)
    print(request.user.employee.company)
    queryset = Employee.objects.filter(company=request.user.employee.company)
    context = {

        'object_list': queryset,
    }
    return render(request, 'base.html', context)  # context)


@login_required
def employee_create(request):

    designation = Designation.objects.filter(
        company=request.user.employee.company)
    job_type = JobType.objects.filter(company=request.user.employee.company)
    department = Department.objects.filter(
        company=request.user.employee.company)

    if request.method == "POST":

        username = request.POST.get('username')
        password = request.POST.get('password1')
        company = request.user.employee.company
        user_form = UserForm(request.POST or None)
        employee_form = AddEmployeeForm(
            request.POST, request.FILES)
        des_history_form = DesignationHistoryForm(request.POST)

        jobtype_history_form = JobTypeHistoryForm(request.POST)

        department_history_form = DepartmentHistoryForm(request.POST)

        print(employee_form.errors, user_form.errors)

        if user_form.is_valid() and employee_form.is_valid() and des_history_form.is_valid() and jobtype_history_form.is_valid() and department_history_form.is_valid:

            try:

                user = user_form.save()
                employee = employee_form.save(commit=False)
                employee.user = user
                employee.company = request.user.employee.company

                employee.save()

                deshistory = des_history_form.save(commit=False)
                deshistory.employee = user.employee
                deshistory.company = request.user.employee.company
                deshistory = des_history_form.save()

                jobtype = jobtype_history_form.save(commit=False)
                jobtype.employee = user.employee
                jobtype.company = request.user.employee.company
                jobtype.date = datetime.datetime.now()
                jobtype.save()

                department_history = department_history_form.save(commit=False)
                department_history.employee = user.employee
                department_history.company = request.user.employee.company
                department_history.date = datetime.datetime.now()
                department_history.save()

                email = user.email
                html_message = loader.render_to_string(
                    'employee_reg_msg.html',
                    {
                        'username': username,
                        'password': password,
                        'subject': 'Thank u for joining in ' + str(company),
                    }
                )

                send_mail('amazatic solutions', 'Congratulations', [
                          email], settings.EMAIL_HOST_USER, fail_silently=False, html_message=html_message)
                messages.success(request, 'Employee add successfull')
                return redirect('employee_list')

            except Exception as e:

                print('Exception Occure..!', e)
        else:
            messages.error(request, 'Form is Not Valid plz ')
            employee_form = AddEmployeeForm()
            user_form = UserForm()
            des_history_form = DesignationHistoryForm()
            jobtype_history_form = JobTypeHistoryForm()
            department_history_form = DepartmentHistoryForm()

            return render(request, 'empEdit.html', {'user_form': user_form, 'employee_form': employee_form, 'des_history_form': des_history_form, 'jobtype_history_form': jobtype_history_form, 'department_history_form': DepartmentHistoryForm})

    else:

        employee_form = AddEmployeeForm()
        user_form = UserForm()
        des_history_form = DesignationHistoryForm()
        jobtype_history_form = JobTypeHistoryForm()
        department_history_form = DepartmentHistoryForm()
        context = {
            'user_form': user_form,
            'employee_form': employee_form,
            'des_history_form': des_history_form,
            'jobtype_history_form': jobtype_history_form,
            'department_history_form': DepartmentHistoryForm
        }

        return render(request, 'empEdit.html', context)


def employee_update(request, pk):

    print(request, pk)
    emp = get_object_or_404(Employee, pk=pk)

    designation = Designation.objects.filter(
        company=request.user.employee.company)

    job_type = JobType.objects.filter(company=request.user.employee.company)

    department = Department.objects.filter(
        company=request.user.employee.company)

    if request.method == "POST":

        employee_form = AddEmployeeForm(request.POST or None,
                                        request.FILES, instance=emp)
        user_form = UserForm(request.POST or None, instance=emp.user)
        des_history_form = DesignationHistoryForm(request.POST)

        jobtype_history_form = JobTypeHistoryForm(request.POST)

        department_history_form = DepartmentHistoryForm(request.POST)

        if employee_form.is_valid() and user_form.is_valid() and des_history_form.is_valid() and jobtype_history_form.is_valid() and department_history_form.is_valid():
            try:

                user = user_form.save()
                emp = employee_form.save()

                deshistory = des_history_form.save(commit=False)
                deshistory.employee = user.employee
                deshistory.company = request.user.employee.company
                deshistory = des_history_form.save()

                jobtype = jobtype_history_form.save(commit=False)
                jobtype.employee = user.employee
                jobtype.company = request.user.employee.company
                jobtype.date = datetime.datetime.now()
                jobtype.save()

                department_history = department_history_form.save(commit=False)
                department_history.employee = user.employee
                department_history.company = request.user.employee.company
                department_history.date = datetime.datetime.now()
                department_history.save()
                return redirect('employee_list')
            except:

                print('Exception Occures at employee_update Viev..!')

    else:

        user_form = UserForm(instance=emp.user)
        employee_form = AddEmployeeForm(instance=emp)
        des_history_form = DesignationHistoryForm()

        jobtype_history_form = JobTypeHistoryForm()

        department_history_form = DepartmentHistoryForm()

        context = {
            'user_form': user_form,
            'employee_form': employee_form,
            'des_history_form': des_history_form,
            'jobtype_history_form': jobtype_history_form,
            'department_history_form': department_history_form,
        }

    return render(request, 'empEdit.html', context)


def employee_home(request):

employee/templates/admin.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block content %}
<!--
     <div class="container mt-5">
     <div class="accordion" id="myaccordion">
     <div class="card ml-20 mr-20">
     <div class="card-header" id="myheader">
     <h5 class="mb-0">
     <button class="btn btn-link" type="button" data-toggele="collapse" data-target="#collapse1" aria-expanded="true" aria-controls="collapse1">
     Todays Mail:</button>
     </h5>
     </div>
     <div id="collapse1" class="collapse show" aria-labelledby="myheader" data-parent="#myaccordion">
     <div class="card-body">
     zhjdhjhfajadhjghdrjng
     </div>
     </div>
     </div>
     </div>
     </div>
-->

<div class="accordion" id="accordionExample">
    <div class="card">
        <div class="card-header" id="headingOne">
            <h5 class="mb-0">
                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Collapsible Group Item #1 <span class="badge badge-pill badge-dark">33</span>
                </button>
            </h5>
        </div>

        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class="card-body">
                ,w;elkjwgjrfdjgjmsdlkjmsalkmdd
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-6">

        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 mt-5 border-bottom">
            <h1 class="h2"><i class="fa fa-bar-chart"></i> {{request.user.employee.company }} Average Salary</h1>
        </div>


      <!--  <div class="container" style="height:50%;width:50%;">-->
            <div id="container"></div>
        </div>
  <!--  </div>-->
        <div class="col-6">

            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 mt-5 border-bottom">
                <h1 class="h2"><i class="fa fa-pie-chart"></i> {{request.user.employee.company }} Employee</h1>
            </div>
            <!--  <div class="container" style="height:50%;width:50%;">-->
            <canvas id="myChart" height="40%" width="50%"></canvas>
        </div>
        <!-- </div>-->
</div>
{% endblock %}

employee/templates/index.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="payroll_logo.png">

        <title>Dashboard</title>
        <!-- Bootstrap Complete CSS V4.0 -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


        <!--Link for Font awesome icons -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://code.highcharts.com/highcharts.src.js"></script>
         <script>
         $(document).ready(function(){
             $("#test").hide();
             $("#id_mark").on("change", function(){
                 $("#test").show();
             });
         });
        </script>

        <!-- Custom styles for this template -->
        <!-- <link href="styles.css" rel="stylesheet">-->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/company.css' %}">
        <link rel="stylesheet" href="{% static 'css/attencence.css' %}">
        <link rel="stylesheet" href="{% static 'css/salary.css' %}">

    </head>

    <body> <!--style="background-image:url('{% static "images/images 10.jpeg" %}')";>-->

        {% if user.is_authenticated %}

        {% if user.is_superuser %}

            <nav class="navbar navbar-dark sticky-top bg-dark ">
                <a class="navbar-brand col-sm-3 " href="#">{{ user.employee.company }} </a>
                <div class="dropdown1">
                    <button class="dropbtn1" style="background:none;"><i class="fa fa-user-circle"></i> Wellcome {{ user.username }}
                    </button>
                    <div class="dropdown1-content1">
                        <a class="dropdown1-item" href="#"><i class="fa fa-key"></i>  Change Password</a>
                        <a class="dropdown1-item" href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> logout</a>
                    </div>
                </div>
            </nav>


            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12 col-md-2">
                        <div class="sidenav">

                            <a href="{% url 'company_display' pk=user.employee.company.pk %}" >
                                <i class="fa fa-home"></i>
                                Company </a>
                            <a href="{% url 'employee_display' pk=user.pk %} ">
                                <i class="fa fa-user-o">
                                </i> Profile
                            </a>

                            <a href="{% url 'employee_list' %}"><i class="fa fa-user-o"></i> Employee
                            </a>


                            <a href="{% url 'add_attendance' %}"><i class="fa fa-file-text"></i> Attendance</a>
                            <a href="{% url 'select_salary' %}"><i class="fa fa-money"></i>  Salary</a>


                        </div><!--Div class sidenav End -->
                    </div><!--Div class col-2 End -->



                    {% else %}


                        <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
                            <a class="navbar-brand col-sm-3 " href="#">{{ user.employee.company }} wnkjjesned</a>
                            <div class="dropdown1">
                                <button class="dropbtn1" style="background:none;"><i class="fa fa-user-circle"></i> Wellcome {{ user.username }}
                                </button>
                                <div class="dropdown1-content1">
                                    <a class="dropdown1-item" href="#"><i class="fa fa-key"></i>  Change Password</a>
                                    <a class="dropdown1-item" href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> logout</a>
                                </div>
                            </div>
                        </nav>

                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-2">
                                <div class="sidenav">

                                    <a href="{% url 'company_display' pk=user.employee.company.pk %}" >
                                        <i class="fa fa-home"></i>
                                        Company </a>
                                    <a href="{% url 'employee_display' pk=user.pk %} ">
                                        <i class="fa fa-user-o">
                                        </i> Profile
                                    </a>

                                    <a href="{% url 'employee_list' %}"><i class="fa fa-user-o"></i> Employee
                                    </a>


                                    <a href="{% url 'add_attendance' %}"><i class="fa fa-file-text"></i> Attendance</a>
                                    <a href="{% url 'select_salary' %}"><i class="fa fa-money"></i>  Salary</a>


                                </div><!--Div class sidenav End -->
                            </div><!--Div class col-2 End -->



                            {% endif%}


                            {% else %}
                            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>

                                <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                                    <a class="navbar-brand" href="#">payroll Management System </a>

                                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

                                        <li class="nav-item active">
                                            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="#">About us</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="#">Services</a>
                                        </li>

                                    </ul>

                                </div>
                            </nav>


                            {% endif %}
                            <div class="col col-sm-12 col-md-10">
                                <div class="main responsive">
                                    {% include 'messages.html'%}
                                    {% block content %}


                                    {% endblock %}
                                </div><!--Div class main End -->
                            </div><!--Div class col-10 End -->
                        </div><!--Div class Row End -->
                    </div>


        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        <!-- Icons -->
        <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
        <script>
         feather.replace()
        </script>

        <!-- Graphs -->
        <!--  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>

        <script>
         var ctx = document.getElementById("myChart").getContext('2d');
         var myChart = new Chart(ctx, {
             type: 'pie',
             data: {
                 // labels: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
                 labels: ["male","Female"],
                 datasets: [{
                     label: '# of Votes',
                     data: [{{m_count}}, {{f_count}}],
                     backgroundColor: [
                         'rgba(255, 99, 132, 0.2)',
                         'rgba(54, 162, 235, 0.2)',
                         'rgba(255, 206, 86, 0.2)',
                         'rgba(75, 192, 192, 0.2)',
                         'rgba(153, 102, 255, 0.2)',
                         'rgba(255, 159, 64, 0.2)'
                     ],
                     borderColor: [
                         'rgba(255,99,132,1)',
                         'rgba(54, 162, 235, 1)',
                         'rgba(255, 206, 86, 1)',
                         'rgba(75, 192, 192, 1)',
                         'rgba(153, 102, 255, 1)',
                         'rgba(255, 159, 64, 1)'
                     ],
                     borderWidth: 1
                 }]
             },
             options: {
                 scales: {
                     yAxes: [{
                         ticks: {
                             beginAtZero:true
                         }
                     }]
                 }
             }
         });

        </script>
        <script>
         Highcharts.chart('container', {
             chart: {
                 type: 'column'
             },
             title: {
                 text: 'Monthly Average Salary'
             },
             // subtitle: {
             //   text: 'Source: WorldClimate.com'
             // },
             xAxis: {
                 categories: [
                     'Jan',
                     'Feb',
                     'Mar',
                     'Apr',
                     'May',
                     'Jun',
                     'Jul',
                     'Aug',
                     'Sep',
                     'Oct',
                     'Nov',
                     'Dec'
                 ],
                 crosshair: true
             },
             yAxis: {
                 min: 0,
                 title: {
                     text: 'salary'
                 }
             },
             tooltip: {
                 headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                 pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                              '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
                 footerFormat: '</table>',
                 shared: true,
                 useHTML: true
             },
             plotOptions: {
                 column: {
                     pointPadding: 0.2,
                     borderWidth: 0
                 }
             },
             series: [{
                 name: 'Tokyo',
                 data: [49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]

             },]
         });
        </script>

        <!--This script for salary_history.html -->
        <script>
         /* $(document).ready(function(){
          *     $(".sachin").show();
          *     //    $("#jadhav").on("click", function(){
          *     $(".jadhav").on("click",function(){
          *         $("#sachin").show();
          *     });
          * });

          */
        </script>
    </body>
</html>